[package]
name = "rocket-collection"
version.workspace = true
edition.workspace = true

[dependencies]
rocket-shared.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
serde_yaml.workspace = true
uuid = { version = "1", features = ["v4"] }
chrono.workspace = true
ulid.workspace = true
