[package]
name = "rocket-http"
version.workspace = true
edition.workspace = true

[dependencies]
rocket-shared.workspace = true
serde.workspace = true
tokio.workspace = true
serde_json.workspace = true
async-trait.workspace = true
chrono.workspace = true
reqwest.workspace = true
sha2.workspace = true
hmac.workspace = true
hex.workspace = true
base64.workspace = true
rand = "0.8"
urlencoding = "2"
tauri = { version = "2" }
