[package]
name = "rocket-app"
version.workspace = true
edition.workspace = true

[dependencies]
rocket-shared.workspace = true
rocket-audit = { path = "../rocket-audit" }
rocket-collection.workspace = true
rocket-environment.workspace = true
rocket-git.workspace = true
rocket-http.workspace = true
rocket-history.workspace = true
rocket-workspace.workspace = true
serde.workspace = true
serde_json = { workspace = true }
serde_yaml.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
chrono.workspace = true
ulid.workspace = true
base64.workspace = true
reqwest.workspace = true
tauri = { version = "2" }

[dev-dependencies]
tempfile = "3"
