[package]
name = "rocket-app"
version.workspace = true
edition.workspace = true

[dependencies]
rocket-shared.workspace = true
rocket-collection.workspace = true
rocket-environment.workspace = true
rocket-git.workspace = true
rocket-http.workspace = true
rocket-history.workspace = true
rocket-workspace.workspace = true
serde.workspace = true
serde_yaml.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
chrono.workspace = true
ulid.workspace = true

[dev-dependencies]
tempfile = "3"
