[package]
name = "rocket-app"
version.workspace = true
edition.workspace = true

[dependencies]
rocket-shared.workspace = true
rocket-collection.workspace = true
rocket-environment.workspace = true
rocket-git.workspace = true
rocket-http.workspace = true
rocket-history.workspace = true
rocket-workspace = { path = "../rocket-workspace" }
serde.workspace = true
async-trait.workspace = true
tokio.workspace = true
log.workspace = true
