[package]
name = "rocket-grpc"
version.workspace = true
edition.workspace = true

[dependencies]
rocket-shared.workspace = true
rocket-collection.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
prost-types = "0.14"
prost-reflect = { version = "0.16", features = ["serde"] }
protox = "0.9"

[dev-dependencies]
prost = "0.14"
