[package]
name = "rocket-scripting"
version.workspace = true
edition.workspace = true

[dependencies]
rocket-shared.workspace = true
rocket-environment.workspace = true
rocket-http.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
