[package]
name = "rocket-scripting"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket-shared = { path = "../rocket-shared" }
rocket-environment = { path = "../rocket-environment" }
rocket-http = { path = "../rocket-http" }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
