[package]
name = "rocket-import"
version.workspace = true
edition.workspace = true

[dependencies]
rocket-shared.workspace = true
rocket-collection.workspace = true
rocket-environment.workspace = true
rocket-workspace.workspace = true
rocket-infra = { path = "../rocket-infra" }
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tracing.workspace = true
tempfile = "3"
zip = "2"

[dev-dependencies]
