[package]
name = "rocket-import"
version.workspace = true
edition.workspace = true

[dependencies]
rocket-shared.workspace = true
rocket-collection.workspace = true
rocket-environment.workspace = true
rocket-workspace = { path = "../rocket-workspace" }
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
