use rocket_http::LoadTestResult;
use rocket_shared::error::{DomainError, DomainResult};

#[derive(Debug, Clone, PartialEq, serde::Deserialize, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub enum ExportFormat {
    Html,
    Csv,
    Json,
    Pdf,
}

pub struct ExportService;

impl ExportService {
    /// Export a `LoadTestResult` to the requested format.
    /// Returns the file content as bytes and the suggested filename extension.
    /// Note: For `Pdf`, the bytes returned are the HTML report — the Tauri
    /// command layer renders it via the webview's print-to-PDF API.
    pub fn export(
        result: &LoadTestResult,
        format: ExportFormat,
    ) -> DomainResult<(Vec<u8>, &'static str)> {
        match format {
            ExportFormat::Html => Ok((Self::to_html(result).into_bytes(), "html")),
            ExportFormat::Csv => Ok((Self::to_csv(result).into_bytes(), "csv")),
            ExportFormat::Json => {
                let json = serde_json::to_string_pretty(result)
                    .map_err(|e| DomainError::Internal(e.to_string()))?;
                Ok((json.into_bytes(), "json"))
            }
            ExportFormat::Pdf => Ok((Self::to_html(result).into_bytes(), "pdf")),
        }
    }

    fn to_csv(result: &LoadTestResult) -> String {
        let mut out = String::from("seq,status,latency_ms,response_bytes,error,phase_index\n");
        for entry in &result.request_log {
            let status = entry.status.map(|s| s.to_string()).unwrap_or_default();
            let error = entry.error.as_deref().unwrap_or("").replace(',', ";");
            out.push_str(&format!(
                "{},{},{:.2},{},{},{}\n",
                entry.seq,
                status,
                entry.latency_ms,
                entry.response_bytes,
                error,
                entry.phase_index,
            ));
        }
        out
    }

    fn to_html(result: &LoadTestResult) -> String {
        let ts_json = serde_json::to_string(&result.time_series).unwrap_or_default();
        let log_json = serde_json::to_string(&result.request_log).unwrap_or_default();

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>RocketAPI Load Test Report</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 1100px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; }}
  h1 {{ font-size: 22px; font-weight: 500; margin-bottom: 4px; }}
  .meta {{ color: #666; font-size: 14px; margin-bottom: 32px; }}
  .kpi-grid {{ display: grid; grid-template-columns: repeat(6, 1fr); gap: 12px; margin-bottom: 32px; }}
  .kpi {{ background: #f5f5f5; border-radius: 8px; padding: 12px; }}
  .kpi-label {{ font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.04em; }}
  .kpi-val {{ font-size: 20px; font-weight: 500; margin-top: 2px; }}
  .charts {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 32px; }}
  .chart-card {{ background: #fff; border: 1px solid #e5e5e5; border-radius: 8px; padding: 16px; }}
  .chart-title {{ font-size: 13px; font-weight: 500; color: #555; margin-bottom: 12px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ background: #f5f5f5; padding: 8px 12px; text-align: left; font-weight: 500; }}
  td {{ padding: 6px 12px; border-bottom: 1px solid #f0f0f0; }}
  .ok {{ color: #0f6e56; }} .err {{ color: #a32d2d; }}
</style>
</head>
<body>
<h1>Load Test Report</h1>
<div class="meta">Generated by RocketAPI</div>
<div class="kpi-grid">
  <div class="kpi"><div class="kpi-label">Total requests</div><div class="kpi-val">{total}</div></div>
  <div class="kpi"><div class="kpi-label">Succeeded</div><div class="kpi-val ok">{succeeded}</div></div>
  <div class="kpi"><div class="kpi-label">Failed</div><div class="kpi-val err">{failed}</div></div>
  <div class="kpi"><div class="kpi-label">Req / sec</div><div class="kpi-val">{rps:.1}</div></div>
  <div class="kpi"><div class="kpi-label">p95 latency</div><div class="kpi-val">{p95:.0}ms</div></div>
  <div class="kpi"><div class="kpi-label">Duration</div><div class="kpi-val">{dur:.1}s</div></div>
</div>
<div class="charts">
  <div class="chart-card"><div class="chart-title">Latency over time (ms)</div><canvas id="latChart"></canvas></div>
  <div class="chart-card"><div class="chart-title">Throughput (req/sec)</div><canvas id="rpsChart"></canvas></div>
  <div class="chart-card"><div class="chart-title">Error rate (%)</div><canvas id="errChart"></canvas></div>
  <div class="chart-card"><div class="chart-title">Active concurrent</div><canvas id="concChart"></canvas></div>
</div>
<h2 style="font-size:16px;font-weight:500;margin-bottom:12px">Request log (last {log_count} entries)</h2>
<table>
  <tr><th>#</th><th>Status</th><th>Latency (ms)</th><th>Size (bytes)</th><th>Error</th></tr>
  <tbody id="log-body"></tbody>
</table>
<script>
const ts = {ts_json};
const log = {log_json};
const labels = ts.map(p => (p.elapsedMs / 1000).toFixed(1) + 's');
function mkChart(id, datasets, yLabel) {{
  new Chart(document.getElementById(id), {{
    type: 'line',
    data: {{ labels, datasets }},
    options: {{ responsive: true, plugins: {{ legend: {{ position: 'top' }} }},
      scales: {{ y: {{ title: {{ display: true, text: yLabel }} }} }} }}
  }});
}}
mkChart('latChart', [
  {{ label: 'p50', data: ts.map(p => p.p50Ms.toFixed(1)), borderColor: '#7F77DD', tension: 0.3, pointRadius: 0 }},
  {{ label: 'p95', data: ts.map(p => p.p95Ms.toFixed(1)), borderColor: '#1D9E75', tension: 0.3, pointRadius: 0 }},
  {{ label: 'p99', data: ts.map(p => p.p99Ms.toFixed(1)), borderColor: '#E24B4A', tension: 0.3, pointRadius: 0 }},
], 'ms');
mkChart('rpsChart', [{{ label: 'req/sec', data: ts.map(p => p.rps.toFixed(1)), borderColor: '#7F77DD', fill: true, backgroundColor: 'rgba(127,119,221,0.1)', tension: 0.3, pointRadius: 0 }}], 'req/sec');
mkChart('errChart', [{{ label: '% error', data: ts.map(p => p.errorRatePct.toFixed(2)), borderColor: '#E24B4A', tension: 0.3, pointRadius: 0 }}], '%');
mkChart('concChart', [{{ label: 'concurrent', data: ts.map(p => p.activeConcurrent), borderColor: '#1D9E75', fill: true, backgroundColor: 'rgba(29,158,117,0.1)', tension: 0.3, pointRadius: 0 }}], 'users');
const tbody = document.getElementById('log-body');
log.forEach(e => {{
  const ok = e.status !== null && e.status < 400;
  tbody.innerHTML += `<tr>
    <td>${{e.seq}}</td>
    <td class="${{ok ? 'ok' : 'err'}}">${{e.status ?? 'ERR'}}</td>
    <td>${{e.latencyMs.toFixed(1)}}</td>
    <td>${{e.responseBytes}}</td>
    <td>${{e.error ?? ''}}</td>
  </tr>`;
}});
</script>
</body>
</html>"#,
            total = result.total_requests,
            succeeded = result.succeeded,
            failed = result.failed,
            rps = result.requests_per_second,
            p95 = result.p95_latency_ms,
            dur = result.total_duration_ms / 1000.0,
            log_count = result.request_log.len(),
            ts_json = ts_json,
            log_json = log_json,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rocket_http::RequestLogEntry;

    fn minimal_result() -> LoadTestResult {
        LoadTestResult {
            total_requests: 2,
            succeeded: 1,
            failed: 1,
            failed_status: 1,
            failed_transport: 0,
            min_latency_ms: 10.0,
            avg_latency_ms: 20.0,
            p50_latency_ms: 20.0,
            p95_latency_ms: 30.0,
            p99_latency_ms: 35.0,
            max_latency_ms: 40.0,
            requests_per_second: 5.0,
            total_duration_ms: 400.0,
            phase_timeline: vec![],
            request_log: vec![
                RequestLogEntry {
                    seq: 0, status: Some(200), latency_ms: 10.0,
                    response_bytes: 100, error: None, phase_index: 0,
                },
                RequestLogEntry {
                    seq: 1, status: Some(500), latency_ms: 30.0,
                    response_bytes: 50, error: None, phase_index: 0,
                },
            ],
            time_series: vec![],
        }
    }

    #[test]
    fn csv_has_header_and_rows() {
        let (bytes, ext) = ExportService::export(&minimal_result(), ExportFormat::Csv).unwrap();
        let s = String::from_utf8(bytes).unwrap();
        assert_eq!(ext, "csv");
        assert!(s.starts_with("seq,status,latency_ms"));
        assert!(s.contains("200"));
        assert!(s.contains("500"));
    }

    #[test]
    fn json_is_valid_and_contains_total() {
        let (bytes, ext) = ExportService::export(&minimal_result(), ExportFormat::Json).unwrap();
        let s = String::from_utf8(bytes).unwrap();
        assert_eq!(ext, "json");
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert_eq!(v["totalRequests"], 2);
    }

    #[test]
    fn html_contains_chart_js_and_kpis() {
        let (bytes, ext) = ExportService::export(&minimal_result(), ExportFormat::Html).unwrap();
        let s = String::from_utf8(bytes).unwrap();
        assert_eq!(ext, "html");
        assert!(s.contains("Chart.js") || s.contains("chart.umd.min.js"));
        assert!(s.contains("Load Test Report"));
    }
}
